apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\Ashbir Dhiman\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f .\docker-compose-services.yml
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: chatbot-product-service
  name: chatbot-product-service
spec:
  ports:
    - name: "29233"
      port: 29233
      targetPort: 29233
  selector:
    io.kompose.service: chatbot-product-service
