apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\Ashbir Dhiman\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f .\docker-compose-services.yml
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: notification-service
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: notification-service
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\Ashbir Dhiman\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f .\docker-compose-services.yml
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: notification-service
    spec:
      containers:
        - env:
            - name: SPRING_APPLICATION_NAME
              value: notification-service
            - name: SPRING_CONFIG_IMPORT
              value: optional:configserver:http://config-server:8888
            - name: SPRING_PROFILES_ACTIVE
              value: default
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
          image: ashbirdhiman/shoppermart-notification-service:latest
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8086
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 5
          name: notification-service
          ports:
            - containerPort: 8086
              protocol: TCP
      restartPolicy: Always
