apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: inventory-service-mysql-claim0
  name: inventory-service-mysql-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
