apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: shoppermart
data:
  SPRING_PROFILES_ACTIVE: kubernetes
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
  SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,info,metrics,prometheus
  LOGGING_LEVEL_ROOT: INFO
  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  SPRING_KAFKA_PRODUCER_KEY_SERIALIZER: org.apache.kafka.common.serialization.StringSerializer
  SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER: org.springframework.kafka.support.serializer.JsonSerializer
  SPRING_KAFKA_CONSUMER_KEY_DESERIALIZER: org.apache.kafka.common.serialization.StringDeserializer
  SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER: org.springframework.kafka.support.serializer.JsonDeserializer
  SPRING_KAFKA_CONSUMER_GROUP_ID: shoppermart-service
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-config
  namespace: shoppermart
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS user_service;
    CREATE DATABASE IF NOT EXISTS order_service;
    CREATE DATABASE IF NOT EXISTS inventory_service;
    GRANT ALL PRIVILEGES ON user_service.* TO 'shoppermart'@'%';
    GRANT ALL PRIVILEGES ON order_service.* TO 'shoppermart'@'%';
    GRANT ALL PRIVILEGES ON inventory_service.* TO 'shoppermart'@'%';
    FLUSH PRIVILEGES;
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: shoppermart
data:
  datasources.yml: |-
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:9090
        isDefault: true

      - name: Loki
        type: loki
        access: proxy
        url: http://loki:3100
        isDefault: false

