spring:
  application:
    name: Inventory-Service
  datasource:
    url: jdbc:mysql://localhost:3308/inventory_service?createDatabaseIfNotExist=true
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
  sql:
    init:
      mode: never

server:
  port: 8083

# Eureka Configuration
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    prefer-ip-address: true

# Actuator & Prometheus
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
      base-path: /actuator
  metrics:
    export:
      prometheus:
        enabled: true
